export default class DemoPrintData {

    print_sdr_015_data() {
        let data = [
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
        ]

        return data
    }
}